---
name: Test

on:                          # yamllint disable-line rule:truthy

  workflow_dispatch:

  push:
    branches-ignore:
      - 'update/**'
      - 'dependabot/**'
    tags:
      - '**'


jobs:

  macOS:
    runs-on:
      - self-hosted
      - Linux

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mark Completed
        run: touch  ${{ runner.temp }}/Green
